# Generated by Django 5.2.1 on 2025-06-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/list_images'),
        ),
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/thing_images'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
