# Generated by Django 5.2.1 on 2025-06-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='comparison_method',
            field=models.CharField(choices=[('bradley_terry', 'Bradley-Terry Model'), ('crowd-bt', 'Crowd-BT Model')], default='bradley_terry'),
        ),
    ]
