# Generated by Django 5.2.1 on 2025-06-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0002_list_description_list_image_list_slug_thing_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
