# Generated by Django 5.2.3 on 2025-06-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0002_alter_list_author_alter_matchup_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='rating',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
    ]
