# Generated by Django 5.2.3 on 2025-06-29 00:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0003_alter_thing_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchup',
            old_name='judge',
            new_name='user',
        ),
        migrations.AddField(
            model_name='seenthing',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
