# Generated by Django 5.2.1 on 2025-06-10 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0003_alter_list_name_alter_list_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
