# Generated by Django 5.2.1 on 2025-07-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0004_rename_judge_matchup_user_seenthing_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='comparison_method',
            field=models.CharField(choices=[('bradley_terry', 'Bradley-Terry Model'), ('crowd-bt', 'Crowd-BT Model')], default='bradley_terry', max_length=20),
        ),
    ]
