# Generated by Django 5.2.1 on 2025-07-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0005_alter_list_comparison_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='author',
            new_name='user',
        ),
    ]
