# Generated by Django 5.2.1 on 2025-06-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0005_alter_list_slug_profile_list_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='num_things',
            field=models.IntegerField(default=0),
        ),
    ]
