# Generated by Django 5.2.1 on 2025-07-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0006_rename_author_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thing',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
