# Generated by Django 5.2.1 on 2025-07-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0007_thing_losses_thing_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='permission',
            field=models.CharField(choices=[('public', 'Public'), ('protected', 'View Only'), ('private', 'Private')], default='public'),
            preserve_default=False,
        ),
    ]
