# Generated by Django 5.2.1 on 2025-07-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0008_list_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_images'),
        ),
    ]
