# Generated by Django 5.2.1 on 2025-07-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0011_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='type',
            field=models.CharField(choices=[('image', 'Images Only'), ('text', 'Text and Images')], default='text'),
        ),
        migrations.AlterField(
            model_name='list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='list_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thing_images/'),
        ),
    ]
