# Generated by Django 5.2.1 on 2025-08-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0012_list_type_alter_list_image_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='permission',
            field=models.CharField(choices=[('public', 'Public'), ('protected', 'View Only'), ('private', 'Private')], default='private'),
        ),
    ]
