# Generated by Django 5.2.1 on 2025-08-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0013_alter_list_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='permission',
            field=models.CharField(choices=[('private', 'Private'), ('protected', 'View Only'), ('public', 'Public')], default='private'),
        ),
    ]
