# Generated by Django 5.2.1 on 2025-08-31 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0015_recentlistinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='permitted_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='permission',
            field=models.CharField(choices=[('private', 'Private'), ('protected', 'View Only'), ('invite-rank', 'Invite to Rank'), ('invite-view', 'Invite to View + Rank'), ('public', 'Public')], default='private', help_text='Controls who can view or participate in ranking this list.', max_length=20),
        ),
        migrations.DeleteModel(
            name='SeenThing',
        ),
    ]
