# Generated by Django 5.2.1 on 2025-08-31 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0016_list_permitted_users_alter_list_permission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='permitted_users',
            field=models.ManyToManyField(related_name='permitted_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
