# Generated by Django 5.2.1 on 2025-08-31 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0017_alter_list_permitted_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchups_lost', to='createList.thing'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchups_won', to='createList.thing'),
        ),
    ]
