# Generated by Django 5.2.1 on 2025-09-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0018_alter_matchup_loser_alter_matchup_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='permission',
            field=models.CharField(choices=[('private', 'Private'), ('protected', 'View Only'), ('invite-rank', 'Invite to Rank'), ('invite-view', 'Invite to View + Rank'), ('public', 'Public')], default='private', help_text='Controls who can view or rank this list.', max_length=20),
        ),
    ]
