# Generated by Django 5.2.1 on 2025-09-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0019_alter_list_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='permission',
            field=models.CharField(choices=[('private', 'Private'), ('protected', 'View Only'), ('invite-rank', 'Invite to Rank'), ('invite-view', 'Invite to View'), ('public', 'Public')], default='private', help_text='Controls who can view or rank this list.', max_length=20),
        ),
    ]
