# Generated by Django 5.2.1 on 2025-09-06 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0021_alter_list_name_alter_list_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Username cannot contain ',' or '@'.", regex='^[^,@]+$')]),
        ),
    ]
