# Generated by Django 5.2.1 on 2025-09-15 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0022_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
